anjanibarlapati/smartchat-frontend

- android/app/src/main/AndroidManifest.xml
- ios/Podfile
- ios/Podfile.lock
- ios/SmartChat/Info.plist
- ios/SmartChat/PrivacyInfo.xcprivacy
- jest.config.ts
- package-lock.json
- package.json
- src/components/ProfilePicturePickerModal/ProfilePicturePickerModal.test.tsx
- src/components/ProfilePicturePickerModal/ProfilePicturePickerModal.tsx
- src/permissions/permissions.ts
- src/screens/Registration/Registration.handler.test.ts
- src/screens/Registration/Registration.handler.ts
- src/screens/Registration/Registration.styles.ts
- src/screens/Registration/Registration.test.tsx
- src/screens/Registration/Registration.tsx
- src/types/InputUser.ts
- src/types/UploadImage.ts
- src/utils/constants.ts
- src/utils/openCamera.ts
- src/utils/openPhotoLibrary.ts
- Integrated React Native permissions for accessing the Photo Library and Camera with an appropriate platform-specific handling.
- Refined state management in the `RegistrationcScreen`.
- Integrated registration form to the backend API to send user details for account creation.
- Added permission handling using react-native-permissions and native modules.
- Made registration flow to backend using `fetch`.
- Added alert dialog boxes for errors.
- Testing for the functionalities done.
> Implement Permissions and Registration screen with backend integration.

- src/screens/Login/Login.handler.test.ts
- src/screens/Login/Login.handler.ts
- src/screens/Login/Login.test.tsx
- src/screens/Login/Login.tsx
- src/screens/Registration/Registration.tsx
- src/types/Credentials.ts
- src/types/LoginCredentials.ts
- This PR implements user login functionality which integrates backend using a fetch request.
- Added login fetch HTTP Post request to hit the backend API with tests. 
- Added user login handler function with tests and error handling.
- Updated login credentials type and removed credentials error type.
> Login screen backend integration.

- src/components/ChatBox/ChatInputBox.test.tsx
- src/components/ChatBox/InputChatBox.styles.ts
- src/components/ChatBox/InputChatBox.test.tsx
- src/components/ChatBox/InputChatBox.tsx
- src/utils/themes.ts
📌What does this pull request accomplish?
* This PR describes about the implementation of inputChatBox Component.
✅Testing:
* Followed TDD and done unit testing using jest and everything is working as expected.
Thank you!
> inputChatBox - Component

- ios/Podfile.lock
- jest.config.ts
- package-lock.json
- package.json
- src/components/ContactCard/ContactCard.test.tsx
- src/components/ContactCard/ContactCard.ts
- src/components/ContactCard/ContactCard.tsx
- src/i18n/translations/english/home.json
- src/i18n/translations/telugu/home.json
- src/navigations/AppNavigator.tsx
- src/redux/reducers/contacts.reducer.ts
- src/redux/reducers/theme.reducer.ts
- src/redux/reducers/user.reducer.ts
- src/redux/store.ts
- src/screens/Contact/Contact.service.test.ts
- src/screens/Contact/Contact.service.ts
- src/screens/Contact/Contact.styles.ts
- src/screens/Contact/Contact.test.tsx
- src/screens/Contact/Contact.tsx
- src/screens/Login/Login.test.tsx
- src/screens/Login/Login.tsx
- src/screens/Profile/Profile.test.tsx
- src/screens/Profile/Profile.tsx
- src/screens/Registration/Registration.test.tsx
- src/screens/Registration/Registration.tsx
- src/types/Contacts.ts
- src/types/User.ts
- src/utils/getContactDetails.test.ts
- src/utils/getContactsDetails.ts
This PR implements contact card and update contact screen, which includes the following:
- Implemented a contact card component which can be reused in contact screen.
- It takes contact as prop which has contact name, contact number, profile picture and a flag.
- Renders invite text based on the flag of the contact that indicates whether the user is on app or not.
- Added a fetch request to make API call to backend to get the contact details of a user.
- Updated contact screen to get the contacts from backend and render them based on the active tab.
- Created a redux reducer to store the contact details.
- Updated the folder structure and updated import statements according to that.
All the Components and screens were implemented following **Test-Driven Development (TDD)** with unit …
> Implement contact card component and update contact screen.

- ios/Podfile.lock
- src/components/Modal/AlertModal.styles.ts
- src/screens/Profile/Profile.test.tsx
- src/screens/Profile/Profile.tsx
This PR describes about the implementaion of Alert Modals in Profile Screen.
- Added alert modal for sign out confirmation. 
- Added alert modal for account delete confirmation
- Tested using Jest and RNTL.
Thank you!
> Implement Alert modals for Signout and Delete functionalities.

- package-lock.json
- package.json
- src/screens/Login/Login.tsx
- src/screens/Registration/Registration.tsx
- src/utils/socket.test.ts
- src/utils/socket.ts
This PR implements socket connection using `socket.io-client` for real-time communication 💬.
-  Establishes a socket connection using a `stored access token`.
- Handled `connect` and `disconnect` events in socket.io. 
- Adds a method `socketDisconnect` to manually terminate the connection.
- Unit tested with `jest` and everything is working as expected ☑️.
> Implement socket connection

- src/components/ChatCard/ChatCard.styles.ts
- src/components/ChatCard/ChatCard.test.tsx
- src/components/ChatCard/ChatCard.tsx
- src/screens/Home/Home.styles.tsx
- src/types/Chat.ts
📌**This PR includes the following changes..**
- Implements a ChatCard component.
- Includes a chat name, latest message and with a time stamp(when it is delivered).
- Render a unread message count badge with a conditional check.
✅Testing
- Component is unit tested with jest and behaving as expected.
> Implement ChatCard UI component

- src/components/Modal/AlertModal.styles.ts
- src/components/Modal/AlertModal.test.tsx
- src/components/Modal/AlertModal.tsx
- src/i18n/translations/english/home.json
- src/i18n/translations/telugu/home.json
- src/navigations/AppNavigator.tsx
- src/screens/Login/Login.tsx
- src/screens/Registration/Registration.tsx
- src/utils/checkToken.test.ts
- src/utils/checkToken.ts
This PR implements accessing using the re-generated access_token.
- Accessed `access_token` and `refresh_token` from user_data and sent it to backend.
-  Once the response from backend is **`OK`**, `newAccessToken` is set to **`EncryptedStorage`**.
- Unit tested using `jest`, used mocking to `mock libraries` and everything is working as expected ☑️.
> Regenerating access_token

- src/components/ProfileInfoTile/ProfileInfoTile.test.tsx
- src/components/ProfileInfoTile/ProfileInfoTile.tsx
- src/components/ProfilePicturePickerModal/ProfilePicturePickerModal.test.tsx
- src/components/ProfilePicturePickerModal/ProfilePicturePickerModal.tsx
- src/screens/Login/Login.tsx
- src/screens/Profile/Profile.handler.test.ts
- src/screens/Profile/Profile.handler.ts
- src/screens/Profile/Profile.test.tsx
- src/screens/Profile/Profile.tsx
- src/screens/Registration/Registration.tsx
- src/types/ProfilePicturePickerModalProps.ts
- src/types/User.ts
- src/utils/Properties.ts
- src/utils/getTokens.ts
This PR describes about the implementaion of Profile screen handlers.
- Added email validation while editing the email in profile screen.
- Implemnent edit profile picture with new one.
- Implement remove profile picture functionality.
- Implement sign out functionality.
- Implement delete account functionality.
- Everything is tested using Jest and RNTL.
Thank you!
> Implement Profile screen handler.

- src/components/ChatHeader/ChatHeader.test.tsx
- src/components/ChatHeader/ChatHeader.tsx
- src/components/ChatOptionsModal/ChatOptionsModal.styles.ts
- src/components/ChatOptionsModal/ChatOptionsModal.test.tsx
- src/components/ChatOptionsModal/ChatOptionsModal.tsx
- src/components/Menu/Menu.test.tsx
- src/components/Menu/Menu.tsx
- src/navigations/stacks/HomeStack.tsx
- src/screens/IndividualChat/IndividualChat.styles.ts
- src/screens/IndividualChat/IndividualChat.test.tsx
- src/screens/IndividualChat/IndividualChat.tsx
- src/types/Navigations.ts
This PR implements Individual Chat Screen along with the following changes:
- This feature implements the Individual Chat Screen, including testing. It involves integrating a customized header, menu, and input box typing component.
- Wrote tests for all the elements of  Individual Chat Screen are unit tested with Jest and are behaving as expected.
- Linting has passed with no errors and warnings.
- All tests passed and everything works as expected.
> Individual Chat Screen

- src/components/ProfileInfoTile/ProfileInfoTile.styles.ts
- src/components/ProfileInfoTile/ProfileInfoTile.tsx
- src/screens/Profile/Profile.test.tsx
- src/screens/Profile/Profile.tsx
- Fixed the edit functionality isssue during navigation, sign out and delete account.
- Modified test cases.
Thank you!
> Fix: Profile Screen edit functionality.

- package-lock.json
- package.json
- src/utils/decryptMessage.test.ts
- src/utils/decryptMessage.ts
- src/utils/encryptMessage.test.ts
- src/utils/encryptMessage.ts
- src/utils/keyPairs.test.ts
- src/utils/keyPairs.ts
This PR implements `public` & `private keys` generation, encryption and decryption of messages.
- Generates  a `publicKey`, `privateKey` using **`react-native-libsodium`** library.
- Adds API requests  for storing and fetching user's `publicKey`. 
- Implements message **encryption** and **decryption** logic.
- Unit tested using `jest` and everything is working as expected ☑️.
> Message encryption decryption

- src/components/ContactCard/ContactCard.test.tsx
- src/components/ContactCard/ContactCard.tsx
- src/navigations/AppNavigator.tsx
- src/types/Navigations.ts
This PR adds navigation for the contact screen to individual chat screen and sending SMS invitation. 
- If a contact have an account on SmartChat, when user click on contact card, then it will navigate to individual chat screen.
- If a contact don't have an  account on SmartChat, then it will send SMS invitation on clicking that contact card.
All test cases are passing and everything is working as expected.
<video  height="800" src="https://github.com/user-attachments/assets/667e1e9d-873f-47b3-92b8-10ece2e5ed53"> 
Thank you!
> Implement navigation for contact screen.

- src/components/ChatBox/InputChatBox.test.tsx
- src/components/ChatBox/InputChatBox.tsx
- src/components/SendButton/SendButton.service.ts
- src/components/SendButton/SendButton.styles.ts
- src/components/SendButton/SendButton.test.tsx
- src/components/SendButton/SendButton.tsx
- src/components/SendButton/sendButton.service.test.ts
- src/navigations/AppNavigator.tsx
- src/redux/reducers/messages.reducer.ts
- src/redux/store.ts
- src/screens/IndividualChat/IndividualChat.styles.ts
- src/screens/IndividualChat/IndividualChat.test.tsx
- src/screens/IndividualChat/IndividualChat.tsx
- src/screens/Login/Login.test.tsx
- src/screens/Login/Login.tsx
- src/screens/Registration/Registration.test.tsx
- src/screens/Registration/Registration.tsx
- src/utils/checkToken.test.ts
- src/utils/checkToken.ts
- src/utils/getContactsDetails.ts
- src/utils/socket.test.ts
- src/utils/socket.ts
- src/utils/themes.ts
- Establishes socket connection and reads the message through new message socket event and decrypts it.
- Stores user messages in redux.
- Stores public key, private key in database and encrypted storage respectively.
- Integrates `postMessage` route when user clicks on send message.
- Renders `messages` in individual chat screen in **`real-time`**.
- All the components and functionalities are unit tested using `jest` and everything is working as expected.
> Implement real time messaging feature

- src/components/ChatOptionsModal/blockChat.service.test.ts
- src/components/ChatOptionsModal/blockChat.service.ts
- src/components/Menu/Menu.test.tsx
- src/components/Menu/Menu.tsx
- src/screens/IndividualChat/IndividualChat.tsx
**This PR adds and updates the block user chat feature.**
* Changes made:
1. Added fetch API call to block a user in chat.
2. Implemented handleBlock function.
3. Added auth token header to blockUserChat.
📌 Added test cases for:
* blockUserChat 
* handleBlock function
* block user fetch API
* Checked ESLint
* All test cases passed and work as expected.
> Block chat api integration

- ios/SmartChat.xcodeproj/project.pbxproj
- ios/SmartChat/LaunchScreen.storyboard
📌 What does this PR do?
* This PR implements the following changes:
- Updates the splash screen for all iOS devices (iPhone and iPad).
- And the splash screen looks good on all screen sizes.
> Update the SplashScreen

- src/components/ChatOptionsModal/unblockChat.service.test.ts
- src/components/ChatOptionsModal/unblockChat.service.ts
- Implement UnblockChat service functionality to make an API request.
- Added test cases to check the functionality.
- Functionality is unit-tested with jest and behaving as expected.
> Implement unblock chat integration service.

- android/app/build.gradle
- android/app/google-services.json
- android/app/src/main/AndroidManifest.xml
- android/build.gradle
- ios/Podfile
- ios/Podfile.lock
- package-lock.json
- package.json
- src/navigations/AppNavigator.tsx
- src/screens/Home/Home.test.tsx
- src/screens/Home/Home.tsx
- src/screens/Login/Login.service.test.ts
- src/screens/Login/Login.service.ts
- src/screens/Login/Login.test.tsx
- src/screens/Profile/Profile.test.tsx
- src/screens/Registration/Registration.service.test.ts
- src/screens/Registration/Registration.service.ts
- src/screens/Registration/Registration.test.tsx
- src/utils/checkToken.test.ts
- src/utils/checkToken.ts
- src/utils/socket.ts
-  Integrated firebase FCM  for android .
-  Added device id to identify active session of the user uniquely.
- Modify login service to include device id during fetch call.
- Handled automatic logout using Websocket events.
- All the functionalities and components are  unit tested with jest and are behaving as expected.
> Implement Firebase integration for android and automatic logout.

- src/components/AlertModal/AlertModal.styles.ts
- src/components/AlertModal/AlertModal.tsx
- src/components/ContactCard/ContactCard.styles.ts
- src/components/ContactCard/ContactCard.tsx
- src/components/CustomAlert/CustomAlert.styles.ts
- src/components/CustomAlert/CustomAlert.test.tsx
- src/components/CustomAlert/CustomAlert.tsx
- src/components/InputField/InputField.styles.ts
- src/components/Menu/Menu.tsx
- src/components/MessageBox/MessageBox.styles.ts
- src/components/MessageBox/MessageBox.tsx
- src/components/ProfileInfoTile/ProfileInfoTile.tsx
- src/components/ProfilePicturePickerModal/ProfilePicturePickerModal.tsx
- src/navigations/AppNavigator.tsx
- src/screens/Contact/Contact.styles.ts
- src/screens/Contact/Contact.tsx
- src/screens/Home/Home.styles.tsx
- src/screens/Home/Home.tsx
- src/screens/Login/Login.styles.ts
- src/screens/Login/Login.tsx
- src/screens/Profile/Profile.styles.ts
- src/screens/Profile/Profile.tsx
- src/screens/Registration/Registration.styles.ts
- src/screens/Registration/Registration.tsx
- src/screens/Unread/Unread.styles.ts
- src/screens/Unread/Unread.tsx
- src/screens/Welcome/Welcome.styles.ts
- src/screens/Welcome/Welcome.tsx
This PR implements adding consistent styling using `useWindowDimensions` react-native hook to apply consistent styles  across all devices.
- It works for all screen dimensions including foldable phone ☑️.
> Consistent Styles

- src/components/AlertModal/AlertModal.test.tsx
- src/components/ContactCard/ContactCard.test.tsx
- src/components/ContactCard/ContactCard.tsx
- src/components/CustomAlert/CustomAlert.test.tsx
- src/components/CustomAlert/CustomAlert.tsx
- src/components/MessageBox/MessageBox.test.tsx
- src/components/MessageBox/MessageBox.tsx
- src/navigations/stacks/HomeStack.tsx
- src/screens/Contact/Contact.test.tsx
- src/screens/Contact/Contact.tsx
- src/screens/Home/Home.test.tsx
- src/screens/Login/Login.test.tsx
- src/screens/Profile/Profile.test.tsx
- src/screens/Registration/Registration.test.tsx
- src/screens/Registration/Registration.tsx
- src/screens/Welcome/Welcome.test.tsx
- src/screens/Welcome/Welcome.tsx
This PR implements updating test cases for all screen styles to test for **different screen dimensions** and cover test-coverage.
> Udpate test cases for all component styles  to cover test-coverage 

- src/screens/Profile/Profile.services.test.ts
- src/screens/Profile/Profile.services.ts
- src/screens/Profile/Profile.test.tsx
- src/screens/Profile/Profile.tsx
This pull request integrates the user logout functionality by calling the logout API and ensures a smooth navigation to the welcome screen upon successful logout.
1. **API Integration:**
- Integrated the `/logout` endpoint to handle user logout request.
- Implemented error handling for API failures during logout.
2. **Navigation Flow:**
- Upon successful logout, the application navigates the user to the WelcomeScreen.
- It also clears the authentication tokens and user data from local storage upon successful logout.
3. **Unit Tests:**
- Added tests for the logout API integration.
- Verified the navigation behaviour after logout in the unit tests.
> Implement logout integration.

- src/realm-database/operations/updateMessageStatus.test.ts
- src/realm-database/operations/updateMessageStatus.ts
- src/types/MessageStatus.ts
- src/utils/constants.ts
- Created an object for mapping message status priority-wise.
- Modified functionality to update status for only relevant messages.
- Added a test case to check status is not updating for blocked message.
- All the functionalities and components are unit-tested with jest and are behaving as expected.
> Fix the message status updation logic and unread messages count.

- .github/workflows/main.yaml
- package-lock.json
- package.json
- src/App/App.test.tsx
- src/App/App.tsx
- src/utils/localNotifications.test.ts
- src/utils/localNotifications.ts
- This PR adds a notification service using @notifee/react-native.
- It includes three main functions:
- initNotifications – requests notification permission and creates a channel.
- sendLocalNotification – displays an immediate local notification.
- scheduleNotification – schedules a notification using a timestamp trigger after a delay.
- Unit tests have been written using Jest for all functions.
- Tests cover success and error handling cases.
- All tests are passing.
- Linting has passed with no errors and warnings.
- All tests passed and everything works as expected.
Here in Android:
> Implement local notification service

- .github/workflows/main.yaml
- index.js
- ios/Podfile.lock
- src/App/App.test.tsx
- src/App/App.tsx
- src/hooks/useFcmListener.test.ts
- src/hooks/useFcmListener.ts
- src/navigations/AppNavigator.test.tsx
- src/navigations/AppNavigator.tsx
- src/redux/reducers/activeChat.reducer.ts
- src/redux/store.ts
- src/screens/IndividualChat/IndividualChat.tsx
- src/utils/decryptMessage.ts
- src/utils/fcmBackgroundHandler.test.ts
- src/utils/fcmBackgroundHandler.ts
- src/utils/localNotifications.ts
This PR implements the both foreground and background notifications of Firebase cloud messaging. It ensures secure and user-friendly notifications.
- Listens to incoming FCM messages when the app is in the **foreground**.
- Decrypts the message body before showing it in the notification.
- Retrieves sender's **contact name** and **profile picture**.
- Sets up `messaging.setBackgroundMessageHandler` to handle notifications when the app is **backgrounded or killed**.
- Displays a **fallback local notification** using `remoteMessage.notification.body` or a default string if body is missing.
- Unit tests added for `HandleIncomingFCM`:
- Displays decrypted message if body is present
- Falls back to default message if body is `undefined`
- Manually verified:
- Local notification displays …
> Implement Foreground & Background Push Notifications

- android/build.gradle
- src/components/InputChatBox/InputChatBox.tsx
**What does this PR do?**
- Updates the InputChatBox component.
- Removes the KeyboardAvoidingView.
- The KeyboardAvoidingView was hiding the InputChatBox in individual chats, so I fixed that issue.
✅ Testing:
- Test cases working as expected.
> Fix input chatbox

- src/navigations/tabs/Tabs.tsx
- src/screens/Profile/Profile.styles.ts
- src/screens/Profile/Profile.test.tsx
- src/screens/Profile/Profile.tsx
- Added keyboard event listener in profile screen and toggled the visibility of bottom tabs appropriately.
- Modified styles in bottom tabs and profile screen.
All the components and functionalities are unit tested with jest and are behaving as expected.
Thank you😊 :).
> Fix bottom tab visibility issue on keyboard open

- src/components/ChatCard/ChatCard.styles.ts
- src/utils/localNotifications.test.ts
- src/utils/localNotifications.ts
- Removes request notification permission as it is already handled in Home Screen.
- Modified tests for local notifications.
- Updated styles for chat card component and fixed unread badge position.
All the components and functionalities are unit tested with jest and are behaving as expected.
> Fix unread badge position in chat card and remove request notification permission.

- src/components/ChatCard/ChatCard.test.tsx
- src/components/ChatCard/ChatCard.tsx
- src/components/ProfilePictureViewer/PofilePictureViewer.tsx
- src/components/ProfilePictureViewer/ProfilePictureViewer.styles.ts
- src/components/ProfilePictureViewer/ProfilePictureViewer.test.tsx
- src/screens/Profile/Profile.test.tsx
- src/screens/Profile/Profile.tsx
- Added ProfilePictureViewer Modal for viewing profile picture on clicking profile images.
- Updated profile screen to view profile picture on clicking the profile"
- Updated ChatCard component with ProfilePictureViewer Modal to view profile pictures.
- Added test cases for  ProfilePictureViewer Modal.
- All the components and functionalities are unit-tested with jest and are behaving as expected.
Thank you😊:)
> Implement ProfilePictureViewer Modal

- src/utils/sendSmsInvite.test.ts
- src/utils/sendSmsInvite.ts
📌 **What does this PR do:**
* Fixed SMS permission check to work properly on Android 14+.
* Changed Android 14+ to open default SMS app instead of sending directly.
✅ Testing:
* Test cases working as expected.
Thank you!
> Fix SMS permission api34 

- .github/workflows/main.yaml
- src/screens/Registration/Registration.test.tsx
- src/screens/Registration/Registration.tsx
- This PR makes input field as required field in registration.
- Added error if email is provided while registering.
- All the code updated in this PR is unit tested with Jest and RNTL and everything is working as expected.
> Make email input as mandatory.

- src/components/ChatHeader/ChatHeader.styles.ts
- src/components/ChatHeader/ChatHeader.test.tsx
- src/components/ChatHeader/ChatHeader.tsx
- src/screens/IndividualChat/IndividualChat.test.tsx
- src/screens/IndividualChat/IndividualChat.tsx
This PR implements checking for receiver's online status and rendering it in the Chat Header.
- Adds a useEffect hook to emit a `check-user-status` event to the server for checking if the chat participant is online.
- Listens for `user-online` and `user-offline` socket events to dynamically update the user’s online status in the UI.
- Updates the `ChatHeader` component to render the user’s online status ("`Online`") under the name.
- Updated tests to handle this, everything is working as expected.
> Online status update
